apiVersion: batch/v1
kind: Job
metadata:
  name: spark-anomaly-detector
spec:
  template:
    spec:
      containers:
      - name: spark-consumer
        image: vital-pulse-spark:v2
        imagePullPolicy: Never 
      restartPolicy: Never